stages:
  - build
  - test
  - publish

include:
# DOCS: https://gitlab.internal.sanger.ac.uk/team113sanger/common/cicd-template/-/blob/develop/README.md
  - project: 'team113sanger/common/cicd-template'
    ref: 0.3.1
    file: '.gitlab-ci-components.yml'

#############
# TEMPLATES #
#############

.generic-wo-script-or-rules:
  extends:
    - .component-variables
    - .component-before_script
    - .component-tags-shared-large-runner

.specific-variables:
  variables:
    UNIT_TEST_MOUNT_POINT: /hairpin2
    RUN_SCRIPT_MOUNT_POINT: /hairpin2/docker_run_unit_tests.sh
    # We need to set this to 1 to enable BuildKit as the Dockerfile uses BuildKit features to speed up the build
    DOCKER_BUILDKIT: 1
    PRE_FETCH_BASE_IMAGE: python:3.12-slim
    # Incase 'docker compose' build is ever used we want to ensure the image
    # does not have sudo. By default CICD jobs do not build with 'docker
    # compose' but use 'docker' - so this is just a safety measure.
    HAS_SUDO: 0

############
#   JOBS   #
############

build:
  stage: build
  extends:
    - .generic-wo-script-or-rules
    - .specific-variables
    - .component-script_docker-build
    - .component-rules-except-release

unit-test:
  stage: test
  extends:
    - .generic-wo-script-or-rules
    - .specific-variables
    - .component-rules-except-release
  script:
    - echo "*** [SCRIPT] START ***"
    - echo "I am a script - I run the Python unit tests in a docker container"
    - echo "Unit test against CANDIDATE_IMAGE='${CANDIDATE_IMAGE:?not-set-in-before_script}'"
    - docker pull "${CANDIDATE_IMAGE}"
    # Test image against unit tests - it requires env vars
    - docker run -e TEST_DIR="${UNIT_TEST_MOUNT_POINT}" -v "${PWD}:${UNIT_TEST_MOUNT_POINT}:ro" -v "${PWD}/docker_run_unit_tests.sh:${RUN_SCRIPT_MOUNT_POINT}:ro" --rm "${CANDIDATE_IMAGE}" bash "${RUN_SCRIPT_MOUNT_POINT}"
    - echo "*** [SCRIPT] END ***"

publish-develop:
  stage: publish
  extends:
    - .generic-wo-script-or-rules
    - .specific-variables
    - .component-script-publish-develop-docker-image
    - .component-rules-develop-only

publish-tagged_and_latest_docker_images:
  stage: publish
  extends:
    - .generic-wo-script-or-rules
    - .specific-variables
    - .component-script-publish-tagged+latest-docker-image
    - .component-rules-tag-only

