[params]
# mark-support and mark-overlap take no params
[params.mark-low-qual]
min_avg_clip_quality = 35
min_mapping_quality = 11
min_base_quality = 25

[params.mark-duplicates]
duplication_window_size = 6

[params.LQF]
read_loss_threshold = 0.99
min_pass_reads = 2
nsamples_threshold = 0

[params.DVF]
read_loss_threshold = 0.49
min_pass_reads = 2
nsamples_threshold = 0

[params.ALF]
avg_AS_threshold = 0.93

[params.ADF]
edge_definition = 0.15
edge_clustering_threshold = 0.9
min_MAD_one_strand = 0
min_sd_one_strand = 4.0
min_MAD_both_strand_weak = 2
min_sd_both_strand_weak = 2.0
min_MAD_both_strand_strong = 1
min_sd_both_strand_strong = 10.0
min_reads = 1
